/**
 * In-game jewel colour for every decoration, keyed by the API decoration name.
 *
 * Generated from the MH Wilds Database (https://wilds.mhdb.io/en/decorations,
 * `icon.color`), matched to our catalog by name + slot size, falling back to
 * the granted skills. Regenerate when the decoration catalog changes.
 */

import type { DecorationColor } from "./decoration-sprite";

export const DECORATION_COLORS: Readonly<Record<string, DecorationColor>> = {
  "Adapt Jewel 1": "gray",
  "Ambush Jewel 2": "purple",
  "Antiblast Jewel 1": "vermilion",
  "Antidote Jewel 1": "purple",
  "Antipara Jewel 1": "yellow",
  "Artillery Jewel 1": "gray",
  "Artillery Jewel II 2": "gray",
  "Artillery Jewel III 3": "gray",
  "Attack Jewel 1": "pink",
  "Attack Jewel II 2": "pink",
  "Attack Jewel III 3": "pink",
  "Bandolier Jewel 1": "blue",
  "Bandolier Jewel II 2": "blue",
  "Bandolier Jewel III 3": "blue",
  "Bandolier-Blaze Jwl 3": "blue",
  "Bandolier-Bolt Jwl 3": "blue",
  "Bandolier-Dragon Jwl 3": "blue",
  "Bandolier-Frost Jwl 3": "blue",
  "Bandolier-Ironwall Jwl 3": "blue",
  "Bandolier-Precise Jwl 3": "blue",
  "Bandolier-Stream Jwl 3": "blue",
  "Blast Jewel 1": "vermilion",
  "Blast Jewel II 2": "vermilion",
  "Blast Jewel III 3": "vermilion",
  "Blastcoat Jewel 2": "vermilion",
  "Blaze Jewel 1": "red",
  "Blaze Jewel II 2": "red",
  "Blaze Jewel III 3": "red",
  "Blaze-Bandolier Jwl 3": "red",
  "Blaze-Crit Elem Jwl 3": "red",
  "Blaze-Enhancer Jwl 3": "red",
  "Blaze-Focus Jewel 3": "red",
  "Blaze-Guardian Jewel 3": "red",
  "Blaze-Handicraft Jwl 3": "red",
  "Blaze-Ironwall Jwl 3": "red",
  "Blaze-KO Jewel 3": "red",
  "Blaze-Opener Jewel 3": "red",
  "Blaze-Precise Jewel 3": "red",
  "Blaze-Quickswitch Jwl 3": "red",
  "Blaze-Rzr Sharp Jwl 3": "red",
  "Blaze-Shield Jewel 3": "red",
  "Blunt Jewel 1": "lemon",
  "Blunt Jewel II 2": "lemon",
  "Blunt Jewel III 3": "lemon",
  "Bolt Jewel 1": "yellow",
  "Bolt Jewel II 2": "yellow",
  "Bolt Jewel III 3": "yellow",
  "Bolt-Bandolier Jwl 3": "yellow",
  "Bolt-Crit Elem Jwl 3": "yellow",
  "Bolt-Enhancer Jwl 3": "yellow",
  "Bolt-Focus Jewel 3": "yellow",
  "Bolt-Guardian Jwl 3": "yellow",
  "Bolt-Handicraft Jwl 3": "yellow",
  "Bolt-Ironwall Jewel 3": "yellow",
  "Bolt-KO Jewel 3": "yellow",
  "Bolt-Opener Jewel 3": "yellow",
  "Bolt-Precise Jewel 3": "yellow",
  "Bolt-Quickswitch Jwl 3": "yellow",
  "Bolt-Rzr Sharp Jwl 3": "yellow",
  "Bolt-Shield Jewel 3": "yellow",
  "Bomber Jewel 1": "vermilion",
  "Botany Jewel 1": "sage-green",
  "Brace Jewel 1": "gray",
  "Chain Jewel 3": "red",
  "Challenger Jewel 3": "red",
  "Charge Jewel 1": "blue",
  "Charge Jewel II 2": "blue",
  "Charge Jewel III 3": "blue",
  "Charge Up Jewel 2": "yellow",
  "Charge Up-Attack Jwl 3": "yellow",
  "Charge Up-Draw Jwl 3": "yellow",
  "Charge Up-Expert Jwl 3": "yellow",
  "Charge Up-Handicraft Jwl 3": "yellow",
  "Charge Up-KO Jewel 3": "yellow",
  "Charge-Handicraft Jwl 3": "blue",
  "Charge-KO Jewel 3": "blue",
  "Climber Jewel 1": "ivory",
  "Counter Jewel 2": "red",
  "Counterattack Jewel 3": "red",
  "Crit Elem Jwl III 3": "ultramarine",
  "Crit Elem-Blaze Jwl 3": "ultramarine",
  "Crit Elem-Bolt Jwl 3": "ultramarine",
  "Crit Elem-Dragon Jwl 3": "ultramarine",
  "Crit Elem-Frost Jwl 3": "ultramarine",
  "Crit Elem-Handicraft Jwl 3": "ultramarine",
  "Crit Elem-Ironwall Jwl 3": "ultramarine",
  "Crit Elem-KO Jewel 3": "ultramarine",
  "Crit Elem-Stream Jwl 3": "ultramarine",
  "Crit Element Jewel 1": "ultramarine",
  "Crit Element Jewel II 2": "ultramarine",
  "Crit Element-Precise Jwl 3": "ultramarine",
  "Crit Stat Jwl III 3": "emerald",
  "Crit Stat-Handicraft Jwl 3": "emerald",
  "Crit Stat-Ironwall Jwl 3": "emerald",
  "Crit Stat-Precise Jwl 3": "emerald",
  "Crit Status Jewel 1": "emerald",
  "Crit Status Jewel II 2": "emerald",
  "Crit Status-KO Jwl 3": "emerald",
  "Critical Jewel 1": "purple",
  "Critical Jewel II 2": "purple",
  "Critical Jewel III 3": "purple",
  "Def Lock Jewel 1": "ivory",
  "Defense Jewel 1": "brown",
  "Destroyer Jewel 2": "gray",
  "Dive Jewel 1": "sky",
  "Dragon Jewel 1": "rose",
  "Dragon Jewel II 2": "rose",
  "Dragon Jewel III 3": "rose",
  "Dragon Res Jewel 1": "rose",
  "Dragon-Bandolier Jwl 3": "rose",
  "Dragon-Crit Elem Jwl 3": "rose",
  "Dragon-Enhancer Jwl 3": "rose",
  "Dragon-Focus Jewel 3": "rose",
  "Dragon-Guardian Jwl 3": "rose",
  "Dragon-Handicraft Jwl 3": "rose",
  "Dragon-Ironwall Jwl 3": "rose",
  "Dragon-KO Jewel 3": "rose",
  "Dragon-Opener Jewel 3": "rose",
  "Dragon-Precise Jewel 3": "rose",
  "Dragon-Quickswitch Jwl 3": "rose",
  "Dragon-Rzr Sharp Jwl 3": "rose",
  "Dragon-Shield Jewel 3": "rose",
  "Drain Jewel 1": "sky",
  "Drain Jewel II 2": "sky",
  "Drain Jewel III 3": "sky",
  "Draincoat Jewel 2": "ivory",
  "Draw Jewel 1": "purple",
  "Draw Jewel II 2": "purple",
  "Draw Jewel III 3": "purple",
  "Earplugs Jewel 2": "white",
  "Enduring Jewel 1": "ivory",
  "Enhancer Jewel 1": "lemon",
  "Enhancer Jewel II 2": "lemon",
  "Enhancer Jewel III 3": "lemon",
  "Enhancer-Blaze Jewel 3": "lemon",
  "Enhancer-Bolt Jewel 3": "lemon",
  "Enhancer-Dragon Jwl 3": "lemon",
  "Enhancer-Frost Jwl 3": "lemon",
  "Enhancer-Handicraft Jwl 3": "lemon",
  "Enhancer-Stream Jwl 3": "lemon",
  "Escape Jewel 1": "white",
  "Evasion Jewel 2": "sky",
  "Expert Jewel 1": "purple",
  "Expert Jewel II 2": "purple",
  "Expert Jewel III 3": "purple",
  "Fire Res Jewel 1": "red",
  "Flash Jewel 1": "yellow",
  "Flawless Jewel 2": "red",
  "Flayer Jewel 3": "white",
  "Flight Jewel 2": "blue",
  "Flight-Attack Jwl 3": "blue",
  "Flight-Draw Jewel 3": "blue",
  "Flight-Expert Jewel 3": "blue",
  "Flight-Handicraft Jwl 3": "blue",
  "Focus Jewel 1": "brown",
  "Focus Jewel II 2": "brown",
  "Focus Jewel III 3": "brown",
  "Focus-Blaze Jewel 3": "brown",
  "Focus-Bolt Jwl 3": "brown",
  "Focus-Dragon Jewel 3": "brown",
  "Focus-Frost Jewel 3": "brown",
  "Focus-Handicraft Jewel 3": "brown",
  "Focus-KO Jewel 3": "brown",
  "Focus-Precise Jewel 3": "brown",
  "Focus-Stream Jewel 3": "brown",
  "Footing Jewel 1": "gray",
  "Foray Jewel 3": "red",
  "Forceshot Jewel 3": "white",
  "Friendship Jewel 1": "white",
  "Frost Jewel 1": "white",
  "Frost Jewel II 2": "white",
  "Frost Jewel III 3": "white",
  "Frost-Bandolier Jwl 3": "white",
  "Frost-Crit Elem Jwl 3": "white",
  "Frost-Enhancer Jwl 3": "white",
  "Frost-Focus Jewel 3": "white",
  "Frost-Guardian Jwl 3": "white",
  "Frost-Handicraft Jwl 3": "white",
  "Frost-Ironwall Jwl 3": "white",
  "Frost-KO Jewel 3": "white",
  "Frost-Opener Jewel 3": "white",
  "Frost-Precise Jewel 3": "white",
  "Frost-Quickswitch Jwl 3": "white",
  "Frost-Rzr Sharp Jwl 3": "white",
  "Frost-Shield Jewel 3": "white",
  "Fungiform Jewel 2": "purple",
  "Furor Jewel 2": "rose",
  "Gambit Jewel 1": "white",
  "Gambit Jewel II 2": "white",
  "Gambit Jewel III 3": "white",
  "Gambit-Handicraft Jwl 3": "white",
  "Gambit-Ironwall Jwl 3": "white",
  "Gambit-KO Jewel 3": "white",
  "Geology Jewel 1": "ivory",
  "Gobbler Jewel 1": "brown",
  "Grinder Jewel 1": "yellow",
  "Grinder Jewel II 2": "yellow",
  "Grinder-Attack Jewel 3": "yellow",
  "Grinder-Draw Jewel 3": "yellow",
  "Grinder-Expert Jewel 3": "yellow",
  "Grinder-Handicraft Jwl 3": "yellow",
  "Grinder-Ironwall Jewel 3": "yellow",
  "Grinder-KO Jewel 3": "yellow",
  "Growth Jewel 1": "purple",
  "Guardian Jewel 1": "white",
  "Guardian Jewel II 2": "white",
  "Guardian Jewel III 3": "white",
  "Guardian-Blaze Jwl 3": "white",
  "Guardian-Bolt Jwl 3": "white",
  "Guardian-Dragon Jwl 3": "white",
  "Guardian-Frost Jwl 3": "white",
  "Guardian-Handicraft Jwl 3": "white",
  "Guardian-Ironwall Jwl 3": "white",
  "Guardian-Stream Jwl 3": "white",
  "Handicraft Jewel 1": "white",
  "Handicraft Jewel II 2": "white",
  "Handicraft Jwl III 3": "white",
  "Hungerless Jewel 1": "brown",
  "Ice Res Jewel 1": "white",
  "Intimidator Jewel 1": "white",
  "Ironwall Jewel 1": "gray",
  "Ironwall Jewel II 2": "gray",
  "Ironwall Jewel III 3": "gray",
  "Jumping Jewel 2": "sky",
  "KO Jewel 1": "yellow",
  "KO Jewel II 2": "yellow",
  "KO Jewel III 3": "yellow",
  "Leap Jewel 1": "ultramarine",
  "Magazine Jewel 1": "gray",
  "Magazine Jewel II 2": "gray",
  "Magazine-Attack Jwl 3": "gray",
  "Magazine-Draw Jwl 3": "gray",
  "Magazine-Expert Jwl 3": "gray",
  "Magazine-Handicraft Jwl 3": "gray",
  "Magazine-Ironwall Jwl 3": "gray",
  "Maintenance Jewel 2": "ivory",
  "Mastery Jewel 3": "white",
  "Medicine Jewel 1": "green",
  "Mighty Jewel 2": "red",
  "Mind's Eye Jewel 1": "rose",
  "Mind's Eye Jewel II 2": "rose",
  "Mind's Eye Jwl III 3": "rose",
  "Mirewalker Jewel 1": "gray",
  "Opener Jewel 1": "white",
  "Opener Jewel II 2": "white",
  "Opener Jewel III 3": "white",
  "Opener-Blaze Jewel 3": "white",
  "Opener-Bolt Jewel 3": "white",
  "Opener-Dragon Jewel 3": "white",
  "Opener-Frost Jewel 3": "white",
  "Opener-Ironwall Jwl 3": "white",
  "Opener-Precise Jewel 3": "white",
  "Opener-Stream Jwl 3": "white",
  "Paracoat Jewel 3": "yellow",
  "Paralyzer Jewel 1": "yellow",
  "Paralyzer Jewel II 2": "yellow",
  "Paralyzer Jwl III 3": "yellow",
  "Pep Jewel 1": "sky",
  "Perfume Jewel 1": "brown",
  "Phoenix Jewel 2": "purple",
  "Physique Jewel 1": "brown",
  "Pierce Jewel 3": "blue",
  "Poison Jewel 2": "purple",
  "Poison-Attack Jewel 3": "purple",
  "Poison-Draw Jewel 3": "purple",
  "Poison-Expert Jwl 3": "purple",
  "Poison-Handicraft Jwl 3": "purple",
  "Poison-Ironwall Jwl 3": "purple",
  "Poison-KO Jewel 3": "purple",
  "Poison-Precise Jwl 3": "purple",
  "Poisoncoat Jewel 2": "purple",
  "Potential Jewel 2": "red",
  "Precise Jewel 1": "pink",
  "Precise Jewel II 2": "pink",
  "Precise Jewel III 3": "pink",
  "Protection Jewel 1": "blue",
  "Quickswitch Jewel 1": "blue",
  "Quickswitch Jewel II 2": "blue",
  "Quickswitch Jewel III 3": "blue",
  "Quickswitch-Blaze Jwl 3": "blue",
  "Quickswitch-Bolt Jwl 3": "blue",
  "Quickswitch-Dragon Jwl 3": "blue",
  "Quickswitch-Frost Jwl 3": "blue",
  "Quickswitch-Handicraft Jwl 3": "blue",
  "Quickswitch-Ironwall Jwl 3": "blue",
  "Quickswitch-KO Jwl 3": "blue",
  "Quickswitch-Stream Jwl 3": "blue",
  "Ranger Jewel 1": "ivory",
  "Razor Sharp Jewel 1": "emerald",
  "Razor Sharp Jewel II 2": "emerald",
  "Razor Sharp-KO Jwl 3": "emerald",
  "Recovery Jewel 1": "green",
  "Refresh Jewel 2": "ivory",
  "Rzr Sharp Jwl III 3": "emerald",
  "Rzr Sharp-Blaze Jwl 3": "emerald",
  "Rzr Sharp-Bolt Jwl 3": "emerald",
  "Rzr Sharp-Dragon Jwl 3": "emerald",
  "Rzr Sharp-Frost Jwl 3": "emerald",
  "Rzr Sharp-Handicraft Jwl 3": "emerald",
  "Rzr Sharp-Ironwall Jwl 3": "emerald",
  "Rzr Sharp-Stream Jwl 3": "emerald",
  "Salvo Jewel 3": "white",
  "Sane Jewel 1": "purple",
  "Satiated Jewel 1": "ivory",
  "Sharp Jewel 1": "rose",
  "Sharp Jewel II 2": "rose",
  "Sharp Jewel III 3": "rose",
  "Sheath Jewel 1": "brown",
  "Shield Jewel 1": "sky",
  "Shield Jewel II 2": "sky",
  "Shield Jewel III 3": "sky",
  "Shield-Blaze Jewel 3": "sky",
  "Shield-Bolt Jewel 3": "sky",
  "Shield-Dragon Jwl 3": "sky",
  "Shield-Frost Jewel 3": "sky",
  "Shield-Handicraft Jwl 3": "sky",
  "Shield-Ironwall Jwl 3": "sky",
  "Shield-Stream Jewel 3": "sky",
  "Shockproof Jewel 1": "gray",
  "Sleep Jewel 1": "sky",
  "Sleep Jewel II 2": "sky",
  "Sleep Jewel III 3": "sky",
  "Sleepcoat Jewel 3": "sky",
  "Sonorous Jewel 2": "white",
  "Sonorous-Attack Jwl 3": "white",
  "Sonorous-Draw Jwl 3": "white",
  "Sonorous-Expert Jwl 3": "white",
  "Sonorous-Handicraft Jwl 3": "white",
  "Sonorous-KO Jewel 3": "white",
  "Specimen Jewel 1": "moss-green",
  "Spread Jewel 3": "moss-green",
  "Sprinter Jewel 1": "brown",
  "Steadfast Jewel 1": "yellow",
  "Stream Jewel 1": "blue",
  "Stream Jewel II 2": "blue",
  "Stream Jewel III 3": "blue",
  "Stream-Bandolier Jwl 3": "blue",
  "Stream-Crit Elem Jwl 3": "blue",
  "Stream-Enhancer Jwl 3": "blue",
  "Stream-Focus Jewel 3": "blue",
  "Stream-Guardian Jwl 3": "blue",
  "Stream-Handicraft Jwl 3": "blue",
  "Stream-Ironwall Jwl 3": "blue",
  "Stream-KO Jewel 3": "blue",
  "Stream-Opener Jwl 3": "blue",
  "Stream-Precise Jewel 3": "blue",
  "Stream-Quickswitch Jwl 3": "blue",
  "Stream-Rzr Sharp Jwl 3": "blue",
  "Stream-Shield Jewel 3": "blue",
  "Survival Jewel 1": "white",
  "Suture Jewel 1": "ivory",
  "Tenderizer Jewel 3": "dark-purple",
  "Throttle Jewel 3": "red",
  "Thunder Res Jewel 1": "yellow",
  "Trueshot Jewel 1": "gray",
  "Trueshot Jewel II 2": "gray",
  "Venom Jewel 1": "purple",
  "Venom Jewel II 2": "purple",
  "Venom Jewel III 3": "purple",
  "Water Res Jewel 1": "blue",
  "Wind Resist Jewel 1": "white",
};
